// Mocks generated by Mockito 5.4.4 from annotations
// in socle/test/features/movies/presentation/blocs/list/movie_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:socle/core/domain/entities/result.dart' as _i3;
import 'package:socle/features/movies/domain/entities/page_of_movies_entity.dart'
    as _i6;
import 'package:socle/features/movies/domain/repositories/movie_repository.dart'
    as _i2;
import 'package:socle/features/movies/domain/usecases/get_movies_by_page_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMoviesByPageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesByPageUseCase extends _i1.Mock
    implements _i4.GetMoviesByPageUseCase {
  MockGetMoviesByPageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Result<_i6.PageOfMoviesEntity>> call(
          _i4.GetMoviesByPageUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Result<_i6.PageOfMoviesEntity>>.value(
            _FakeResult_1<_i6.PageOfMoviesEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i6.PageOfMoviesEntity>>);
}
