#!/bin/sh
file=test/coverage_helper_test.dart
app_package=socle
echo "// ### GENERATED FILE - DO NOT EDIT ###\n" > $file
echo "// Helper file to make coverage work for all dart files" >> $file
echo "// generated by tools/generate_import_file_test.sh\n" >> $file
echo "// ignore_for_file: unused_import" >> $file
echo "// ignore_for_file: directives_ordering" >> $file
find lib -type f -name '*.dart' \
  | sed 's|.*g.dart||g' \
  | sed 's|.*freezed.dart||g' \
  | sed 's|.*widgetbook.dart||g' \
  | sed 's|.*_state.dart||g' \
  | sed 's|.*_event.dart||g' \
  | sed 's|.*_injection.dart||g' \
  | sed 's|.*_plugin_registrant.dart||g' \
  | cut -c4- \
  | awk -v package=$app_package '$1 != "" {printf "import '\''package:%s%s'\'';\n", package, $1}' >> $file
echo "\nvoid main(){}" >> $file
